"""create restaurants, users and favourites

Revision ID: 88f6ae5f2eda
Revises: 
Create Date: 2026-10-01 23:50:28.093948

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88f6ae5f2eda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Added by hand: the spatial column type below needs PostGIS, and a fresh managed
    # database does not have it enabled.
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_type', sa.Text(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('cuisines', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('diets', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.CheckConstraint("category IN ('restaurant', 'cafe', 'fast_food')", name=op.f('ck_restaurants_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants')),
    sa.UniqueConstraint('osm_type', 'osm_id', name='uq_restaurants_osm')
    )
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_restaurants_location', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
        batch_op.create_index('ix_restaurants_cuisines', ['cuisines'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_restaurants_diets', ['diets'], unique=False, postgresql_using='gin')

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('favourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_favourites_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favourites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'restaurant_id', name=op.f('pk_favourites'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    op.drop_table('users')
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurants_diets', postgresql_using='gin')
        batch_op.drop_index('ix_restaurants_cuisines', postgresql_using='gin')
        batch_op.drop_geospatial_index('idx_restaurants_location', postgresql_using='gist', column_name='location')

    op.drop_geospatial_table('restaurants')
    # ### end Alembic commands ###
